USE photo_portal;
SELECT NAME FROM user 
WHERE (SELECT COUNT(*) FROM photo_post 
WHERE CREATION_DATE >= CURDATE() 
AND CREATION_DATE < DATE_ADD(CURDATE(),INTERVAL 1 DAY)
AND USER_ID = user.USER_ID) > 3;